<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Vietnam</name>
   <tag></tag>
   <elementGuidId>8f2e9158-30d8-4858-8c39-f6f55e732f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'select2-results__option select2-results__option--highlighted' and (text() = '${country}' or . = '${country}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-billing_country-result-cmrn-VN' and (text() = 'Vietnam' or . = 'Vietnam')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>60659f50-a612-4c60-aa84-86c4d53edd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>a66fe795-3117-4da7-a5d8-16d3ec54b7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_country-result-cmrn-VN</value>
      <webElementGuid>f5db3d98-f42a-466a-a08c-a07addc346bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6cb9fe05-2c9c-4770-9036-031a41a08a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>087efb86-ce06-4774-9a4a-5fa2f76ebe30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e1e1b321-a3e5-4429-8faf-fd8c3ac0bc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a96f3de6-809b-48b3-9e6a-8c2c44b7aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${country}</value>
      <webElementGuid>bee8f15d-2883-4c0f-8168-9e5c489f72f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_country-result-cmrn-VN&quot;)</value>
      <webElementGuid>3ddbd0ff-7c40-40a2-b9dd-501cbf74e312</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-billing_country-result-cmrn-VN' and (text() = 'Vietnam' or . = 'Vietnam')]</value>
      <webElementGuid>e4ef5571-0181-4332-823b-3f1faf98e193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
