<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_stanbul</name>
   <tag></tag>
   <elementGuidId>3f93b4ec-d299-4a5a-943a-4aaf5579c5ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'select2-results__option select2-results__option--highlighted' and (text() = 'İstanbul' or . = 'İstanbul')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-billing_state-result-9rfg-TR34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-billing_state-result-9rfg-TR34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>57612191-48dc-4593-be0b-2622098a3627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>446e941b-760e-4b4f-917c-ce385ac57fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_state-result-9rfg-TR34</value>
      <webElementGuid>cc2e9621-540e-4b87-ac8c-d17b737eb9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>501d3625-7671-4105-8f7f-980ee2a4feed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>33b4b8fd-1446-42fc-973f-31f6aebf314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f58bdfbe-f21a-409a-bd0f-d6d79b427b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>843b7da3-17ef-426c-a069-a2fce847b922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${billingProvince}</value>
      <webElementGuid>9266bd78-1d82-434a-877a-e190113c8526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_state-result-9rfg-TR34&quot;)</value>
      <webElementGuid>8a239d00-c9c6-4110-8851-e68e02928c12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-billing_state-result-9rfg-TR34']</value>
      <webElementGuid>5f746d12-9903-485a-87a2-8c3f955c7349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-billing_state-results']/li[34]</value>
      <webElementGuid>a5398232-5e76-4c36-a246-098df33f7d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='İçel'])[2]/following::li[1]</value>
      <webElementGuid>c0d80783-37c1-413d-92ae-46666411a01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isparta'])[2]/following::li[2]</value>
      <webElementGuid>b5bccb1e-cfe6-41df-9ff0-aea8124182ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='İzmir'])[2]/preceding::li[1]</value>
      <webElementGuid>68da7409-e51a-4334-b1a4-d08996a0dc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kars'])[2]/preceding::li[2]</value>
      <webElementGuid>e62d8e42-bbec-4729-9a92-0387b43eb8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[34]</value>
      <webElementGuid>8e8783a2-b35f-4fb0-9193-9819e634c048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-billing_state-result-9rfg-TR34' and (text() = 'İstanbul' or . = 'İstanbul')]</value>
      <webElementGuid>686d1cb8-bea9-411d-93a0-eafa61e2b988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
