<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Press  to jump to the search boxtest   _849522</name>
   <tag></tag>
   <elementGuidId>3f5aaec1-7ad8-4c49-a5b4-5396e582c40e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.A8SBwf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='tsf']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2805d61-8477-4cc7-b80c-6043a0459e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>cnjECf</value>
      <webElementGuid>85c99f0c-879f-42bc-88a2-030d0398225e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsmodel</name>
      <type>Main</type>
      <value>VYkzu kjkykd a4L2gc LM7wx BFDhle gx0hCb TnHSdd L97mud </value>
      <webElementGuid>ee29864d-6ce5-4af7-a272-ff138f78895e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>A8SBwf</value>
      <webElementGuid>8e2f6aaf-0424-444c-b44c-31b05f9d3254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-adhe</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>331d7f7f-159c-46c8-b448-ff64baac9644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alt</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b42882e3-3c8b-4b84-bebc-ae980486ccc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ehswwf</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ada9009-a163-4c9c-81e5-82efcd88bc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hp</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e62bd2d4-db08-4334-b36e-9649d8b61164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mof</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9ebddb30-8a41-4c6b-a1d0-953b6d7eb2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsdata</name>
      <type>Main</type>
      <value>LVplcb;_;</value>
      <webElementGuid>716f4a87-14a1-4908-b651-6a63d68d873a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>lX6RWd:w3Wsmc;ocDSvd:duwfG;DR74Fd:KyvVPe;DkpM0b:d3sQLd;IQOavd:dFyQEf;XzZZPe:jI3wzf;Aghsf:AVsnlb;iHd9U:Q7Cnrc;f5hEHe:G0jgYd;vmxUb:j3bJnb;nTzfpf:YPRawb;R2c5O:LuRugf;qiCkJd:ANdidc;htNNz:SNIJTd;NOg9L:HLgh3;uGoIkd:epUokb;zLdLw:eaGBS;H9muVd:J4e6lb;djyPCf:nMeUJf;hBEIVb:nUZ9le;rcuQ6b:npT2md</value>
      <webElementGuid>c0c838e1-6e6e-4cc9-935f-99658ee13934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Press / to jump to the search boxtest                   See moreDeleteDeleteReport inappropriate predictionsDismiss</value>
      <webElementGuid>0a086ac7-17bf-4cde-8e7b-cb7aabfeb5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsf&quot;)/div[1]/div[@class=&quot;A8SBwf&quot;]</value>
      <webElementGuid>47de9509-73be-4177-9bea-638ce7a1605e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tsf']/div/div</value>
      <webElementGuid>9a56dbd6-dc2f-494f-af88-91968fb1d597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility feedback'])[1]/following::div[5]</value>
      <webElementGuid>ba506054-01ff-4622-bf22-546808d19684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility help'])[1]/following::div[8]</value>
      <webElementGuid>bea8b89c-e091-4d5f-bb4c-e38844db2a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>3427b96d-d8df-4a45-b08c-16aee3bbfb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Press / to jump to the search boxtest                   See moreDeleteDeleteReport inappropriate predictionsDismiss' or . = 'Press / to jump to the search boxtest                   See moreDeleteDeleteReport inappropriate predictionsDismiss')]</value>
      <webElementGuid>82924d19-7caf-4609-972f-30f2cc068f58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
