<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_btnK (1)</name>
   <tag></tag>
   <elementGuidId>2972dd71-c8cc-48e9-ac0a-1cc5488d63e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btnK&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btnK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9efb23a8-7a2b-4869-a6be-fb7a7e792f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gNO89b</value>
      <webElementGuid>59cd8d68-5027-4297-ac7c-b606508901df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Google Search</value>
      <webElementGuid>83fd13ff-ea6b-4ca6-ae69-e022367c94fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Google Search</value>
      <webElementGuid>5f6a93ed-bdf7-4e2e-8178-c101b53904d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnK</value>
      <webElementGuid>ca4ccf93-c8fb-4733-8874-814b71f5f745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97ce31c4-b636-4daa-a337-887be4b743f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>941de6b2-6a2e-47b4-9314-6040df3a2edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>16a854e1-679a-4bc9-8cf9-3c9db1aa9609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>0ahUKEwj0w-q-s6SCAxVtklYBHfzLDhsQ4dUDCAo</value>
      <webElementGuid>b2e9bdc7-9844-4946-ae76-ec9ca15c7c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf emcav&quot;]/div[@class=&quot;UUbT9 EyBRub&quot;]/div[@class=&quot;aajZCb&quot;]/div[@class=&quot;lJ9FBc&quot;]/center[1]/input[@class=&quot;gNO89b&quot;]</value>
      <webElementGuid>1a3c23c4-60db-4ddc-9771-83fd6535697c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btnK']</value>
      <webElementGuid>28683d4a-6700-436d-aa9e-d9cf8b53f762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b4810256-7849-4c36-879c-07c14137692f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnK' and @type = 'submit']</value>
      <webElementGuid>614e3dbb-8e25-415d-ac93-b2c71e956aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
